### DISCUSSION TITLE
Homarr dashboard top left not colored

### DISCUSSION THREAD

**Discussion by FasteryXD** [homarr-labs/homarr#1989] [Ideas]
I wanted to introduce the idea of making the heading with the Homarr symbol at the top left colored again, using the previously selected colors. Looked more lively in the old version.

![IMG_20241025_150057~2](https://github.com/user-attachments/assets/34188087-31f5-43cb-b37e-e24ae734bb14)

**Comment by SeDemal** [comment]
```CSS
.mantine-AppShell-header{
  .mantine-Title-root {
    background-image: linear-gradient(to right, var(--mantine-color-primaryColor-text), var(--mantine-color-secondaryColor-text));
    background-clip: text;
    color: transparent;
  }
}
```
Temporary fix, enter it as custom css on your board
