### DISCUSSION TITLE
Homarr keeps resetting after a reboot

### DISCUSSION THREAD

**Discussion by decompile1** [homarr-labs/homarr#2510] [Q&A]
Everytime I reboot my ubuntu server, homarr loses all of its data and I need to configure it all again every single time. 

my current  docker compose
```
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=d8b6e872d1a7288a2e636e30f1fdb102be8a0065c17371faaaf0ed0a2fde279a
    ports:
      - '7575:7575'
```
