### DISCUSSION TITLE
docker compose部署出错，采用mariadb10，其他用到此数据库的都在正常运行

### DISCUSSION THREAD

**Discussion by vlianx** [homarr-labs/homarr#2977] [Q&A] [answered]
docker compose.yaml
 ```
version: '3.8'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: registry.cn-hangzhou.aliyuncs.com/docker609/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./appdata:/appdata
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - SECRET_ENCRYPTION_KEY=69e95adaaf523b06b4fbb6a3580a8fd88973684d10fc9fd10b5a2c25af62920e
      - DB_DRIVER=mysql2
      - DB_DIALECT=mysql
      - DB_HOST=192.168.8.236
      - DB_PORT=3306
      - DB_NAME=homarr
      - DB_USER=homarr
      - DB_PASSWORD=Homarr@homarr
    ports:
      - '7575:7575'
```

[日志.log](https://vlian5.github.io/cc.ods.im/homarr.html)
