### ISSUE TITLE
bug: 500 internal server error after latest update SECRET_ENCRYPTION_KEY #2240

### ISSUE THREAD

**Issue by IIIdefconIII** [homarr-labs/homarr#1836]
### Describe the bug

I posted it on th wron homarr GH page before and i was tought posting it here:

Environment
Docker

Version
f1962bc5e43

Describe the problem
nvalid environment variables: {
SECRET_ENCRYPTION_KEY: [

Logs
❌ Invalid environment variables: {
SECRET_ENCRYPTION_KEY: [
'SECRET_ENCRYPTION_KEY is required, please generate a 64 character secret in hex format or use the following: "RANDOMNUMBER"'
]
}

Context
Since the update im getting an 500: internal server error

![image](https://github.com/user-attachments/assets/b1aa74c7-bc27-49de-97d9-829782579a0a)

### Steps to reproduce

I was just updated automaticly and recieve this error

### Impact

Huge, nothing is working the page isnt loading anymore

### Additional information

![image](https://github.com/user-attachments/assets/dd50aaaa-8a0e-4587-85f7-f7ba4006ca31)

### Version

1.0.0-beta

### Installation method

Docker Compose

### Browser

Firefox
```
Docker-Compose:
#--------------Dashboards-------------#
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:beta
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/homarr/appdata:/appdata
      - $DOCKERDIR/homarr/wallpapers/:/app/public/img
    ports:
      - 7575:7575
    labels:
      ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"
      org.hotio.pullio.discord.webhook: https://discord.com/api/webhooks/xxxx
      org.hotio.pullio.author.avatar: https://raw.githubusercontent.com/walkxcode/Dashboard-Icons/main/png/homarr.png
```
