### ISSUE TITLE
bug: 500'ing right when spinning up a new container

### ISSUE THREAD

**Issue by dvdpearson** [homarr-labs/homarr#1865]
### Describe the bug

Logs
```
eZ [TRPCClientError]: fetch failed
    at eZ.from (/app/apps/nextjs/.next/server/src/middleware.js:5:3550)
    at /app/apps/nextjs/.next/server/src/middleware.js:5:9616
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  cause: Error: fetch failed
      at context.fetch (/app/node_modules/next/dist/server/web/sandbox/context.js:296:38)
      at tn (/app/apps/nextjs/.next/server/src/middleware.js:5:7790)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ti (/app/apps/nextjs/.next/server/src/middleware.js:5:7892) {
    cause: Error: connect ECONNREFUSED 172.29.0.2:3000
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '172.29.0.2',
      port: 3000
    }
  },
  shape: undefined,
  data: undefined,
  meta: undefined
}
```

### Steps to reproduce

My docker-compose:

```
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr-beta
    image: ghcr.io/homarr-labs/homarr:beta
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=XXXXXX # <--- can be generated with `openssl rand -hex 32`
      - PORT=7572
    ports:
      - '7572:7572'
```

### Impact

Cannot load at all

### Version

1.0.0-beta

### Installation method

Docker Compose

### Browser

Chrome
