### ISSUE TITLE
feat: kubernetes integration

### ISSUE THREAD

**Issue by oben01** [homarr-labs/homarr#1868]
### Describe the feature you'd like to request

I’d like to propose a new feature for Homarr: **Kubernetes Integration**. This feature would enable Homarr to interact with Kubernetes clusters and display cluster information in a read-only mode in the first iteration. Below are the details of how this could be implemented and the tools required.

### Objective: 

- Enable Homarr to interact with Kubernetes clusters in a secure and minimal way.
- Provide a dashboard-like view to display cluster information (e.g., Pods, Services, Deployments) in a read-only mode during the first iteration.

### Helm Chart : 
To access the Kubernetes API, we need to configure specific Kubernetes resources.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homarr-sa
  namespace: homarr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homarr
  name: homarr-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homarr-rolebinding
  namespace: homarr 
subjects:
  - kind: ServiceAccount
    name: homarr-sa
    namespace: homarr
roleRef:
  kind: Role
  name: homarr-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homarr-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "persistentvolumes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homarr-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: homarr-sa
    namespace: homarr
roleRef:
  kind: ClusterRole
  name: homarr-cluster-role
  apiGroup: rbac.authorization.k8s.io
```
/!\ Add  **serviceAccountName: homarr-sa** to the deployement

### Homarr : 

- Add [kubernetes-client](https://github.com/kubernetes-client/javascript) as a dependency for communication with Kubernetes APIs.
- Use tools like kind/minikube for local testing and cluster emulation.
- Leverage development tools like [skaffold](https://skaffold.dev/) or [telepresence](https://www.telepresence.io/) to proxy traffic between the local development environment and the Kubernetes cluster.

### Questions for Discussion:

1. Do you see any limitations or risks in this approach, especially regarding permissions or dependencies?

2. Should we consider additional features or integrations for future iterations, such as write operations or monitoring metrics?

3. Would this feature align with Homarr’s long-term roadmap, and are there any alternative approaches you’d suggest?

Looking forward to your thoughts and feedback!

(Edit by maintainer)
Reference to old issue https://github.com/ajnart/homarr/issues/1421
