### ISSUE TITLE
bug: Installation guide doesn't provide persistance for Portainer stack install

### ISSUE THREAD

**Issue by FlamebergUA** [homarr-labs/homarr#1950]
### Describe the bug

Restarting portainer/docker wipes all data when following current installation procedure described in https://deploy-preview-113--homarr-docs.netlify.app/docs/getting-started/installation/docker/ or https://deploy-preview-113--homarr-docs.netlify.app/docs/getting-started/installation/portainer

Seems like current setup doesn't provide persistance for data/volumes.

I lack technical knowledge re how this works, but I was able to fix it myself. Not sure if my fix is applicable to everyone.

### Steps to reproduce

1. Install Docker and Portainer
2. Add stacks via Portainer
3. Copy docker-compose.yml code from https://deploy-preview-113--homarr-docs.netlify.app/docs/getting-started/installation/portainer into Portainer new stack window
4. Run, add credentials, etc.
5. Restart docker or container itself
6. Your data should disappear

### Impact

Major: losing data is critical to being able to use Homarr.

### Additional information

Docker-compose available here https://deploy-preview-113--homarr-docs.netlify.app/docs/getting-started/installation/portainer

```
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - <your-path>/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=your_64_character_hex_string # <--- can be generated with `openssl rand -hex 32`
    ports:
      - '7575:7575'
```

Docker-compose.yaml I used that fixed my issue:

```
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:beta
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr_data:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=mykey
    ports:
      - '7575:7575'


# Volumes
volumes:
  # Define a named volume for data persistence
  homarr_data:
```

The difference is in mapping /appdata to homarr_data (not subfolder) and defining homarr_data volume in the end. 
Again, I have 0 skill in this, so this might be somehow incorrect, but I know for sure that the code provided in the instructions did not provide persistance to my instance of Homarr. 

Also, please note that beta repo doesn't have 'latest' flag, so Portainer wasn't able to pull it. It worked after changin 'latest' to 'beta'.

### Version

1.0.0-beta

### Installation method

Portainer

### Browser

Firefox

**Comment by Meierschlumpf** [comment]
Hey @FlamebergUA how did you set your volume previously? Like `./directory/appdata:/appdata`, `directory/appdata:/appdata` or what?

**Comment by FlamebergUA** [comment]
The not-working solution was both with ./directory/appdata:/appdata, and directory/appdata:/appdata (as it is now in the documentation).

I think that adding this solved it, but, unfortunately, I'm not too experienced with Docker/Portainer, so can't vouch for that.
```
volumes:
  homarr_data:
```

**Comment by Meierschlumpf** [comment]
Okay I'll test it on my machine as well and if this is the case we'll need to modify the documentation 👍🏼

**Comment by Meierschlumpf** [comment]
Okay, so I tried it out myself on my machine. I created a new stack `homarr-test-stack` and added the homarr docker compose:

```yml
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr-whatever
    image: ghcr.io/homarr-labs/homarr:beta
    restart: unless-stopped
    volumes:
      - ./hello_world/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=mysecret # <--- can be generated with `openssl rand -hex 32`
    ports:
      - '9315:7575'
```

Then I deployed the stack and accessed `localhost:9315` where I created an initial user and a board with an item. After that I restarted the container first from within the portainer dashboard, all things stayed the same, then from docker desktop, everything stayed the same and finally I changed the image tag to:

```yml
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr-whatever
    image: ghcr.io/homarr-labs/homarr:dev
    restart: unless-stopped
    volumes:
      - ./hello_world/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=mysecret # <--- can be generated with `openssl rand -hex 32`
    ports:
      - '9315:7575'
```

and updated the stack with repulling. It created a seperate container so the original one was still running, then it removed the old one and I was still able to access the board with my item on it. So I guess it's not a wide spread issue and more likely was an issue with your specific setup. Thank you anyways for creating the issue 👍🏼
