### ISSUE TITLE
bug: Authentik OIDC login error "Configuration"

### ISSUE THREAD

**Issue by bannert1337** [homarr-labs/homarr#2007]
### Describe the bug

I configured Homarr to use OIDC with Authentik.
When I click `Login with Authentik` the site reloads.
A notification is shown:
```
Login successful
You are now logged in
```

The only relevant output of the browser console it this:
```
GET https://example.com/auth/login?error=Configuration [HTTP/2 200  101ms]
```

### Steps to reproduce

`compose.yml`:
```yaml
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server. #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    env_file: [.env]
    restart: unless-stopped
    volumes:
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=75239150d0de49c4a3c79e64b820492d50fcce6ff5e8fb0ad1e667bae95675f0
    ports:
      - '7575:7575'
```

`.env`:
```shell
AUTH_PROVIDERS=credentials,oidc
AUTH_OIDC_ISSUER="https://auth.example.com/application/o/homarr"
AUTH_OIDC_CLIENT_SECRET="nLjJQX2KCeSYgRt3Mz7ZGHiyj9WBAepMBxj5iF8ZaY1jVgZlq3CZkC2tb6NBzTzYvoxFj4dodiPXA1eIJLrRE1fwrd52xwWieFoZ8VNrEdgDIM6SJ3PUMzoXO2KnhQQS"
AUTH_OIDC_CLIENT_ID="nmw3zoTnYGd0jhFbaff7XrN5Nlt8yfFD7LUNp4Vm"
AUTH_OIDC_CLIENT_NAME="Authentik"
AUTH_OIDC_AUTO_LOGIN=false
```

### Impact

 I can't log in using OIDC through my Authentik IdP.

### Version

Other (describe in "additional information")

### Installation method

Docker Compose

### Browser

Firefox
