### ISSUE TITLE
bug: Cannot connect to nzbget

### ISSUE THREAD

**Issue by diogovalentte** [homarr-labs/homarr#2022]
### Describe the bug

I imported my data from <v.1 version and the nzbget integration is the only one not working. When I try to save, it shows `Creation failed
The integration could not be created`. In the dev tools the request returns:

```json
{"json":{"0":[[0],[null,0,0]]}}
{"json":[0,0,[[{"error":{"message":"Unauthorized","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"integration.create","zodError":null,"error":null}}}]]]}
```

I checked and the credentials are correct. I tried using the container name + port as I used in <v1 `http://nzbget:6798` and using the reverse-proxy `https://nzbget.domain.com`, but nothing worked.

### Steps to reproduce

1. Try to add the nzbget integration with correct credentials and fail.

### Impact

No workarounds.

### Additional information

homarr docker-compose.yml:
```yml
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    volumes:
      - /Apps/homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:3000
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
```

nzbget docker-compose.yml:
```yml
services:
  nzbget:
    container_name: nzbget
    image: nzbgetcom/nzbget:latest
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    name: homelab-net
```

### Version

1.0.0

### Installation method

Portainer

### Browser

Firefox
