### ISSUE TITLE
bug: ECONNREFUSED every time Homarr is reloaded

### ISSUE THREAD

**Issue by infinicode** [homarr-labs/homarr#2167]
### Describe the bug

Hello, 

I am getting a lot of these errors whenever Homarr is reloaded. This slows down loading the page. This wasn't happening before1.x.x. The initial load was snappy. With the current version, loading homarr is taking longer.

```
...
 << query  #23 app.byId  {
  input: { id: 'tyz08p5bym4rxf4sijamrh6d' },
  result: Error [TRPCClientError]: fetch failed
      at g.from (.next/server/chunks/5088.js:89:445939)
      at <unknown> (.next/server/chunks/5088.js:89:452800) {
    shape: undefined,
    data: undefined,
    meta: undefined,
    [cause]: TypeError: fetch failed
        at async Object.fetch (.next/server/chunks/5088.js:89:451997) {
      [cause]: [AggregateError: ] { code: 'ECONNREFUSED' }
    }
  },
  elapsedMs: 568
}
 << query  #24 app.byId  {
  input: { id: 'vrs8cts6axqrf2xsb1gevbnj' },
  result: Error [TRPCClientError]: fetch failed
      at g.from (.next/server/chunks/5088.js:89:445939)
      at <unknown> (.next/server/chunks/5088.js:89:452800) {
    shape: undefined,
    data: undefined,
    meta: undefined,
    [cause]: TypeError: fetch failed
        at async Object.fetch (.next/server/chunks/5088.js:89:451997) {
      [cause]: [AggregateError: ] { code: 'ECONNREFUSED' }
    }
  },
  elapsedMs: 569
}
 << query  #25 app.byId  {
  input: { id: 'pmw8la7p9222befs1hkzn9fa' },
  result: Error [TRPCClientError]: fetch failed
      at g.from (.next/server/chunks/5088.js:89:445939)
      at <unknown> (.next/server/chunks/5088.js:89:452800) {
    shape: undefined,
    data: undefined,
    meta: undefined,
    [cause]: TypeError: fetch failed
        at async Object.fetch (.next/server/chunks/5088.js:89:451997) {
      [cause]: [AggregateError: ] { code: 'ECONNREFUSED' }
    }
  },
  elapsedMs: 571
}
...
```

### Steps to reproduce

1. Connect to homarr url
2. Login
3. >> Errors appear on log
4. Refresh page
5. >> Errors appear on log

### Impact

The application works but the load time has increased.

### Additional information

docker-compose-yaml

```
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /docker/homarr/data:/appdata
    ports:
      - '7575:7575'
    dns_search: internal.domain
    environment:
      SECRET_ENCRYPTION_KEY: "xxxxxxxxx"
```

### Version

1.3.0

### Installation method

Docker Compose

### Browser

Chrome
