### ISSUE TITLE
bug: download widget not updating in real-time

### ISSUE THREAD

**Issue by SandroBarillaPXL** [homarr-labs/homarr#2258]
### Describe the bug

When downloading something with Deluge, the current entry in the download widget doesn't update in real-time. See screenshot below where the values in the widget don't match the values in the Deluge web UI
![Image](https://github.com/user-attachments/assets/d27f5ce6-5f29-4d52-891a-e004cd2668ac)

### Steps to reproduce

1. add deluge integration
2. add download widget and select deluge integration
3. start a download with deluge
4. refresh the page to see the new entry
5. don't see any values changing
6. refresh the page again
7. see updated (but still static) values

### Impact

The widget being live is its reason of existing. If I have to refresh the page all the time, it misses its use.

### Additional information

Same issue on chrome and edge, and same issue I think with the Dash.- widget. Maybe those two are related?

### Version

1.4.0

### Installation method

Docker Compose

### Browser

Chrome

**Comment by manuel-rw** [comment]
Hi, please provide your logs and docker compose.

**Comment by SandroBarillaPXL** [comment]
[_homarr_logs.txt](https://github.com/user-attachments/files/18704318/_homarr_logs.txt)
Logs got collected from portainers, as it seems that the logs screen inside homarr doesn't work as well anymore. I've seen it work in V1.0 I think I remember

docker compose:
```
services:
    homarr:
        container_name: homarr
        image: ghcr.io/homarr-labs/homarr:latest
        ports:
            - 9595:7575
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/homarr/appdata:/appdata
            - /var/lib/homarr/icons:/app/apps/nextjs/public/custom-images
        environment:
            - SECRET_ENCRYPTION_KEY=XXXXX
        restart: always 

    deluge:
        container_name: deluge
        image: lscr.io/linuxserver/deluge:latest
        ports:
          - 8112:8112
          - 6881:6881
          - 6881:6881/udp
        # - 58846:58846 #optional Default deluged port for thin client connectivity
        environment:
          - PUID=128 #sonarr
          - PGID=1002 #servarr
          - TZ=Etc/UTC
        volumes:
          - /var/lib/deluge-c/deluge:/config
          - /mnt/Seagate_4TB/Torrents:/mnt/Seagate_4TB/Torrents
        restart: no
```
