### ISSUE TITLE
bug: Switched from SQLite to MySQL (Maria) and now crashes

### ISSUE THREAD

**Issue by YouveGotMeowxy** [homarr-labs/homarr#2304]
### Environment

Docker

### Version

latest as of this post

### Describe the problem

Per the title, fresh default install (sqlite) seemingly went fine (no errors); switched to MariaDB, and the log now looks like this:

![Image](https://github.com/user-attachments/assets/905f6f3f-977f-4c33-9d0d-6394afb98e20)

Also, when navigating to any other page, I get this:

```
 Error [TRPCError]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(select json_array(`groupMembers_group`.`id`, `groupMembers_group`.`name`, `g...' at line 1
    at E.query (.next/server/chunks/5143.js:164:51965)
    at I.execute (.next/server/chunks/5143.js:170:27462)
    at QueryPromise.execute (.next/server/chunks/5143.js:164:121934)
    at QueryPromise.then (.next/server/chunks/5143.js:170:55294) {
  code: 'INTERNAL_SERVER_ERROR',
  digest: '140570336',
  [cause]: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(select json_array(`groupMembers_group`.`id`, `groupMembers_group`.`name`, `g...' at line 1
      at E.query (.next/server/chunks/5143.js:164:51965)
      at I.execute (.next/server/chunks/5143.js:170:27462)
      at QueryPromise.execute (.next/server/chunks/5143.js:164:121934)
      at QueryPromise.then (.next/server/chunks/5143.js:170:55294) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sql: "select `groupMembers`.`group_id`, `groupMembers`.`user_id`, `groupMembers_group`.`data` as `group` from `groupMember` `groupMembers` left join lateral (select json_array(`groupMembers_group`.`id`, `groupMembers_group`.`name`, `groupMembers_group`.`owner_id`, `groupMembers_group_boardPermissions`.`data`) as `data` from (select * from `group` `groupMembers_group` where `groupMembers_group`.`id` = `groupMembers`.`group_id` limit 1) `groupMembers_group` left join lateral (select coalesce(json_arrayagg(json_array(`groupMembers_group_boardPermissions`.`board_id`, `groupMembers_group_boardPermissions`.`group_id`, `groupMembers_group_boardPermissions`.`permission`)), json_array()) as `data` from `boardGroupPermission` `groupMembers_group_boardPermissions` where `groupMembers_group_boardPermissions`.`group_id` = `groupMembers_group`.`id`) `groupMembers_group_boardPermissions` on true) `groupMembers_group` on true where `groupMembers`.`user_id` = 'ziim6'",
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(select json_array(`groupMembers_group`.`id`, `groupMembers_group`.`name`, `g...' at line 1"
  }
}
2025-02-10T03:27:36.815Z info: ? Connection (1) 1006 
Killed
Container stopped
```

The initial db migrate did seem to populate the MySQL db, so it seems the connection itself shouldn't be the problem.

Running this in docker swarm, here is my Compose:

<details>
  <summary>Expand</summary>

  ```
  homarr:
    hostname: 'homarr'
    image: 'ghcr.io/homarr-labs/homarr:latest'
    environment:
      TZ: 'America/Chicago'
      DB_DRIVER: 'mysql2'
      DB_DIALECT: 'mysql'
      DB_HOST: 'mariadb'
      DB_PORT: '3306'
      DB_NAME: 'homarr'
      DB_USER: 'oc_homarr'
      DB_PASSWORD: '<redacted>'
      SECRET_ENCRYPTION_KEY: 'redacted'
    volumes:
      - '/opt/docker/configs/homarr/appdata:/appdata:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      mode: 'global'
      labels:
        swag.uptime-kuma.enabled: "true"
        swag.uptime-kuma.monitor.name: "Homarr"
        swag.uptime-kuma.monitor.url: "https://homarr.mydomain.com"
        swag.uptime-kuma.monitor.description: "Server Managment"
        swag.uptime-kuma.monitor.parent: "HOMEPAGES"
        com.ouroboros.enable: 'true'
      resources:
        limits:
          memory: '200M'
      restart_policy:
        condition: 'any'
    networks:
      - 'mariadb'
  ```

</details>

### Please tick the boxes

- [x] I confirm that I attached the proper logs
- [x] I've read the [docs](https://github.com/ajnart/homarr#readme)
- [x] I've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
- [x] I've tried to debug myself

### Steps to reproduce

1. Install fresh as usual (w/out MySQL environment vars in compose).
2. Run it in the browser as usual, setup everything as usual.
3. Shut it down.
4. Add MySQL env vars (I use latest maria)
5. Restart container

It's wonky from there on. Sometimes it appears to load normally in the browser, but then you click things and it acts up. White pages, errors, etc.

### Impact

Becomes unusable.

### Additional information

Originally posted here: https://github.com/ajnart/homarr/issues/2274#issue-2841260669

MariaDB Info:

![Image](https://github.com/user-attachments/assets/b416f9e4-af5e-4cf0-a821-237c93a91400)

Homarr version:

![Image](https://github.com/user-attachments/assets/ae768533-f174-4eb3-a47a-7fec02a4ac9e)

### Version

1.5.0

### Installation method

Docker Compose

### Browser

Brave
