### ISSUE TITLE
Broken 0.x version, need to manually import data to 1.0

### ISSUE THREAD

**Issue by janaxhell** [homarr-labs/homarr#2498]
I just realized that Homarr moved to 1.0 with breaking changes and in fact my docker instance suddenly broke (posted issue on old git getting no reply). When I tried to deploy 1.0, it asked me to import data.zip from previous version, but I cannot export that because previous version is broken, it only says "internal server error". 
I have tried to zip the whole content of `:/app/data` and give it to IMPORT tab, but after doing stuff for a while, nothing happened. 
So, is there a way/hierarchy to manually make a compatible data.zip?

**Comment by manuel-rw** [comment]
Just to clarify, you're getting the ``internal server error`` on the version 0.15.10?
If yes, can you please post your logs

**Comment by janaxhell** [comment]
I don't know the version, it the most :latest of `ghcr.io/ajnart/homarr` which I see has now changed to` ghcr.io/homarr-labs/homarr`

This is the log I've posted here https://github.com/homarr-labs/homarr/issues/2498

```
Exporting hostname...
Migrating database...
yarn run v1.22.19
$ tsx ./migrate.ts
Done in 2.25s.
Starting production server...
Listening on port 7575 url: http://orangepi3-lts:7575
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
Error: connect ECONNREFUSED ::1:41779
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1571:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 41779
}
```

**Comment by manuel-rw** [comment]
And what is your docker compose / run command?
Please remove the secret encryption key before posting.

**Comment by janaxhell** [comment]
There was no secret in version 0.x

```
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
     - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/homarr/configs:/app/data/configs
     - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/homarr/icons:/app/public/icons
     - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/homarr/data:/data
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
```
