### ISSUE TITLE
bug: no icons to choose when adding an app

### ISSUE THREAD

**Issue by megamanzteam** [homarr-labs/homarr#2661]
### Describe the bug

I am having an issue getting the "built-in" icons to load in my container in Qnap server via container station 3.

### Steps to reproduce

Fresh install, no icons. Can't pull from repositories.

### Impact

No clean look from no icons.

### Additional information

I have allowed ```cdn.jsdelivr.net``` through my router. If I do a fresh install on a VM of truenas scale I do not have this issue. Both are going through the same router. I have not setup any blocking in the qnap firewall for cdn.jsdelivr.net, it is allowed as well.
compose:
```
name: homarr
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/data/config/homarr-config:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=you can't see me
    restart: unless-stopped
```

I have tried restarting the container a few times to see if that would help with no real luck.

### Version

1.11.0

### Installation method

Docker Compose

### Browser

Firefox
