### ISSUE TITLE
bug: Azure AD / Entra ID authentication not working - logging not helpfull

### ISSUE THREAD

**Issue by ieugen** [homarr-labs/homarr#3051]
### Describe the bug

Hello, 

I've chose homarr because of OIDC support and tried to configure it but auth fails. 
I also did not find any way to enable logging for the authentication process.

- LOG_LEVEL does not show anything for auth.
- AUTH_DEBUG (from next-auth) also does not work 

```
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:02.284Z info: Dispatching request https://login.microsoftonline.com/REDACTED/v2.0/.well-known/openid-configuration (5 headers)
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:03.109Z info: ➖ Connection (1) 1001
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:03.626Z info: Dispatching request https://login.microsoftonline.com/REDACTED/v2.0/.well-known/openid-configuration (5 headers)
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:03.666Z info: ➕ Connection (2) GET /websockets
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:03.667Z info: tRPC request from unknown by user 'undefined (undefined)'
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:03.827Z info: Dispatching request https://login.microsoftonline.com/REDACTED/oauth2/v2.0/token (8 headers)
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:04.118Z error: Read more at https://errors.authjs.dev#callbackrouteerror name="a" type="CallbackRouteError" kind="error"
core_homarr.1.4kign4dj83so@infra1    |     at ih (/app/apps/nextjs/.next/server/chunks/9903.js:411:19308)
core_homarr.1.4kign4dj83so@infra1    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
core_homarr.1.4kign4dj83so@infra1    |     at async iy (/app/apps/nextjs/.next/server/chunks/9903.js:411:26438)
core_homarr.1.4kign4dj83so@infra1    |     at async ib (/app/apps/nextjs/.next/server/chunks/9903.js:411:31170)
core_homarr.1.4kign4dj83so@infra1    |     at async c (/app/apps/nextjs/.next/server/app/api/auth/[...nextauth]/route.js:1:2735)
core_homarr.1.4kign4dj83so@infra1    |     at async tf.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:18835)
core_homarr.1.4kign4dj83so@infra1    |     at async tf.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:23727)
core_homarr.1.4kign4dj83so@infra1    |     at async doRender (/app/node_modules/next/dist/server/base-server.js:1513:42)
core_homarr.1.4kign4dj83so@infra1    |     at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1915:28)
core_homarr.1.4kign4dj83so@infra1    |     at async NextNodeServer.renderPageComponent (/app/node_modules/next/dist/server/base-server.js:2403:24)
core_homarr.1.4kign4dj83so@infra1    | caused by [object Object]
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:04.379Z info: tRPC request from server-fetch by user 'undefined (undefined)'
core_homarr.1.4kign4dj83so@infra1    | 2025-05-07T22:09:04.388Z info: tRPC request from server-fetch by user 'undefined (undefined)'
```

### Steps to reproduce

I'm deploying the app as a docker swarm service behind traefik service using the following definition:

I've created an App Registration in Azure Portal. 
I've added a Web Application with a redirect URL of https://dash.example.com/api/auth/callback/oidc
I've created a client secret .

Side note: I believe supporting OpenID Connect PKCE might be a safer and simpler way to implement OIDC. 

```
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.19.0
    # ports:
      # - '7575:7575'
    volumes:
      - /drevidence/jenkins-ci/homarr-dashboard:/appdata
    environment:
      # - LOG_LEVEL=debug
      - SECRET_ENCRYPTION_KEY=REDACTED
      - BASE_URL=https://dash.example.com
      - NEXTAUTH_URL=https://dash.example.com
      - AUTH_PROVIDERS=credentials,oidc
      - AUTH_DEBUG=true
      - AUTH_OIDC_CLIENT_ID=REDACTED
      - AUTH_OIDC_CLIENT_SECRET="REDACTED"
      - AUTH_OIDC_ISSUER=https://login.microsoftonline.com/REDACTED/v2.0
      - AUTH_OIDC_CLIENT_NAME=Azure
      - AUTH_OIDC_SCOPE_OVERWRITE=openid email profile
      - AUTH_OIDC_ADMIN_GROUP=REDACTED_GROUP_ID
      - AUTH_OIDC_OWNER_GROUP=REDACTED_GROUP_ID
      - AUTH_OIDC_GROUPS_ATTRIBUTE=roles
     # - AUTH_OIDC_FORCE_USERINFO=true
    networks:
      - traefik-infra
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 128m
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname == infra1"
      labels:
        traefik.enable: "true"
        traefik.swarm.network: traefik-infra
        traefik.constraint-label: traefik-infra
        traefik.http.routers.homarr-http.rule: Host(`dash.example.com`)
        traefik.http.routers.homarr-http.entrypoints: http
        traefik.http.routers.homarr-http.middlewares: https-redirect@file
        traefik.http.routers.homarr-https.rule: Host(`dash.example.com`)
        traefik.http.routers.homarr-https.entrypoints: https
        traefik.http.routers.homarr-https.tls: "true"        
        traefik.http.routers.homarr-https.service: homarr
        traefik.http.routers.homarr-https.tls.certresolver: le-tls-challange
        traefik.http.services.homarr.loadbalancer.server.port: "7575"

```

### Impact

I can't easily use the app for my use case - provide a dashboard for people in the organization that only they can edit. 

Manually creating users is not sustainable. 

### Version

1.19.0

### Installation method

Docker Compose

### Browser

Firefox
