### ISSUE TITLE
bug: Releases widget rate limited by GitHub

### ISSUE THREAD

**Issue by monesje** [homarr-labs/homarr#3137]
### Describe the bug

Hey folks!! I'm getting an error with the new (and absolutely incredible) releases widget. The error I'm getting (below) seems to say that GitHub has rate limited the requests. I have 10 apps within the widget connected to GitHub. 

```
{
  "message": "API rate limit exceeded for {my_IP}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

### Steps to reproduce

1. Load up a bunch of Repositories to the releases widget, all using GitHub. 
2. Wait and see. 

### Impact

This effectively makes the releases widget unusable 😟 

I'm probably going to just try other repositories too and see if there's the same issue, but since I fetch through github, I'd like that to be the source of truth for this widget. 

### Additional information

Operating system: Synology DS-423+, on DSM 7.2.2-72806 Update 3. 
Homarr: 1.20.0
Configuration: 
```
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:v1.20.0
    restart: unless-stopped
    volumes:
      - ./homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY={my_precious}
      - DOCKER_HOSTNAMES=socket-proxy
      - DOCKER_PORTS=2375
    ports:
      - '5006:7575'
    security_opt: #new
      - no-new-privileges:true
```

<img width="1554" alt="Image" src="https://github.com/user-attachments/assets/436642d4-937b-4ea4-ae60-88666fe60742" />

<img width="519" alt="Image" src="https://github.com/user-attachments/assets/e89ee4c8-6aeb-4e56-a537-503af7c70c5d" />

Other relevant information:
- Running within a compose project in Synology's Container Manager.

### Version

1.20.0

### Installation method

Synology

### Browser

Chrome
