### ISSUE TITLE
bug: Homarr forgot AGAIN my dashboard

### ISSUE THREAD

**Issue by janaxhell** [homarr-labs/homarr#3233]
### Describe the bug

After yesterday's update, Homarr has AGAIN forgot my dashboard, when I opened it today, it asked me either to start from scratch or import from before 1.0. Since this already happened with no interaction on my part on an Orange Pi 3 LTS, I thought it was some issue with that device, so I deployed it again on an Orange Pi 3B, manually relinking all the missing icons, because there was no obvious way to backup a post-1.0 dashboard. Now it happened again. 

### Steps to reproduce

See above

### Impact

Totally unreliable software.

### Version

1.21.0

### Installation method

Docker Compose

### Browser

Firefox

**Comment by manuel-rw** [comment]
Hi, so first sorry that this happened to you.
Can you please post your docker compose?
You likely forgot some mount paths and hence the data is not persisted on your host.

**Comment by janaxhell** [comment]
This is the same compose I used when I first found out you moved to 1.0 with no mention of breaking changes and I couldn't restore any backup because I was already in a broken 1.0. Restarted from scratch recycling the old json, this worked fine for some time. then it broke. 

```
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-527624aa-65d1-4566-b5fb-293480445b06/Config/homarr/configs:/app/data/configs
      - /srv/dev-disk-by-uuid-527624aa-65d1-4566-b5fb-293480445b06/Config/homarr/icons:/app/public/icons
      - /srv/dev-disk-by-uuid-527624aa-65d1-4566-b5fb-293480445b06/Config/homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
#     - NEXTAUTH_URL: https://XXXXXXXXXXXXXXXXXXXXX
      - SECRET_ENCRYPTION_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - '7575:7575'
```
