### ISSUE TITLE
bug: Unable to view, manage or create boards after migration

### ISSUE THREAD

**Issue by YotamKorah** [homarr-labs/homarr#3358]
### Describe the bug

I tried migrating from 0.15.10 to 1.23.0 and even after the import is done "succesfully" I am still unable to see my boards nor create new ones.
I tried importing with and without them with no change.
I also tried both Firefox and Chrome with the same result

### Steps to reproduce

Installed following [this doc](https://homarr.dev/docs/getting-started/installation/helm)

values:

```yaml
image:
  tag: v1.23.0
persistence:
  homarrDatabase:
    enabled: true
    storageClassName: "<storage_class_name>"
    size: "200Mi"
  homarrImages:
    enabled: true
    storageClassName: "<storage_class_name>"
    size: "1Gi"
service:
  enabled: true
rbac:
  enabled: true
strategyType: "Recreate"
ingress:
  enabled: false
envSecrets:
  dbCredentials:
    existingSecret: db-secret
    existingSecretKey: db-encryption-key
env:
  TZ: "Asia/Jerusalem"
  AUTH_PROVIDERS: "oidc"
  AUTH_OIDC_AUTO_LOGIN: "true"
  AUTH_OIDC_CLIENT_NAME: "Login with OIDC"
  AUTH_OIDC_ISSUER: "https://<my oidc provider>"
```

### Impact

Practically unusable. Users cannot view their boards and admins cannot manage or create new ones.

### Additional information

Viewing a board:

![Image](https://github.com/user-attachments/assets/d869c795-dfae-4382-9e2a-5db59b28bfca)

Management page:

![Image](https://github.com/user-attachments/assets/25d1f673-1f3d-487c-a0f6-e0ff88074b9b)

Boards management page:

![Image](https://github.com/user-attachments/assets/7c596f82-f543-46ab-9e32-d267a00e77f3)

### Version

1.23.0

### Installation method

Helm

### Browser

Firefox
